[project]
name = "panasonicmemoryrecaller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "htpy>=25.6.2",
    "jinja2>=3.1.6",
    "sanic[ext]>=25.3.0",
    "tortoise>=0.1.1",
    "tortoise-orm>=0.25.1",
]
